project_id = "zhojnzbnjtpdeshkdwcb"

[functions.create-pix-payment]
verify_jwt = true

[functions.check-payment-status]
verify_jwt = true

[functions.mercadopago-webhook]
verify_jwt = false

[functions.create-mercadopago-payment]
verify_jwt = false

[functions.get-mp-public-key]
verify_jwt = false

[functions.process-payment-queue]
verify_jwt = false