// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhojnzbnjtpdeshkdwcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpob2puemJuanRwZGVzaGtkd2NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNzE5NzksImV4cCI6MjA3MTY0Nzk3OX0.KWG4ddtKiI7jyUGyFlngTvPUMJxqr2hGc3lqgM85aWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});